name: workflow

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  mi-job:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Permisos de ejecucion
        run: 'chmod +x mvnw'

      - name: Compilar
        run: './mvnw compile --no-transfer-progress'

      - name: Permisos de escritura
        run: 'chmod +w mvnw'

      - name: Ejecutar test
        run: './mvnw verify --no-transfer-progress'

      - name: Publish Test Report
        uses: ctrf-io/github-test-reporter@v1
        with:
          report-path: 'target/surefire-reports/*.xml'
          github-report: true
        if: always()

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true